#!/bin/bash
# runB3
#
export HOME="/home/georges"

sudo chmod 777 /dev/ttyACM0

#
# launch JACK audio server daemon
# jackd -d <audio-interface-backend>
/usr/bin/jackd -Rd alsa &
sleep 5
#
#
# start the B3 emulator
#/opt/setbfree/bin/setBfree -c /home/georges/Documents/B3-Clone-Documents/default.cfg -p /home/georges/Documents/B3-Clone-Documents/default.pgm &
/opt/setbfree/bin/setBfreeUI &
sleep 5
#
#
# build a MIDI port from a COM one
# ttymidi -s <serial-device> -n <alsa-midi-client-name> 
/usr/local/bin/ttymidi -s /dev/ttyACM0 -n kb_out -v &
sleep 1
#
#
# Alsa to Jack MIDI Daemon
# for every ALSA sequencer port, we get one Jack MIDI port
# a2jmidid -e (also export MIDI hardware ports, not only software)
#          -u (ommit the numeric ALSA client ID so that jack_connect
#              can always use the same a2j output name)
/usr/bin/a2jmidid -e -u &
sleep 2
#
#
# connect keyboards control board to setBfree
/usr/bin/jack_connect 'a2j:kb_out (capture): MIDI out'  'setBfree:midi_in' &
sleep 1
#
#
#
#
# Ready !!!
